version: '3'
services:
    cypress-heroes:
        container_name: cypress-heroes
        ports:
            - 3000:3000
            - 3001:3001
        command: dev
        build:
            context: .
            dockerfile: docker/Dockerfile
