version: '3'
services:
    cypress-heroes:
        container_name: cypress-heroes
        network_mode: host
        ports:
          - 3000:3000
        command: dev
        build:
            context: .
            dockerfile: docker/Dockerfile
