version: '3'

tasks:
    app:install:
        cmds:
            - yarn --cwd ./app install
            - yarn setup

    app:dev:
        cmds:
            - yarn dev

    app:up:
        cmds:
            - docker compose up --build -d

    app:down:
        cmds:
            - docker compose down

    cy:install:
        cmds:
            - yarn install

    cy:open:
        cmds:
            - yarn cypress open

    test:
        cmds:
            - yarn cypress run --browser=chrome

    test:smoke:
        cmds:
            - yarn cypress run --env tags="@smoke" --browser=chrome

    test:reports:
        cmds:
            - yarn reports
