version: '3'

tasks:
    install:
        cmds:
            - yarn install
            - yarn setup

    dev:
        cmds:
            - yarn dev

    up:
        cmds:
            - docker compose up --build -d

    down:
        cmds:
            - docker compose down

    open:
        cmds:
            - yarn cypress open

    test:
        cmds:
            - yarn cypress run --browser=chrome

    test:smoke:
        cmds:
            - yarn cypress run --env tags="@smoke" --browser=chrome

    reports:
        cmds:
            - yarn reports
