version: '3'

tasks:
    install:
        cmds:
            - yarn install

    app:setup:
        cmds:
            - yarn run setup

    app:dev:
        cmds:
            - yarn run dev

    app:up:
        cmds:
            - docker compose up --build -d

    app:down:
        cmds:
            - docker compose down
            
    open:
        cmds:
            - npx cypress open

    test:
        cmds:
            - npx cypress run

    test:smoke:
        cmds:
            - npx cypress run --env tags="@smoke"
