version: '3'

tasks:
    install:
        cmds:
            - yarn install

    setup:
        cmds:
            - yarn setup

    dev:
        cmds:
            - yarn dev

    up:
        cmds:
            - docker compose up --build -d

    down:
        cmds:
            - docker compose down

    open:
        cmds:
            - yarn cypress open

    test:
        cmds:
            - yarn cypress run

    test:smoke:
        cmds:
            - yarn cypress run --env tags="@smoke"
