name: Cypress Tests

on: pull_request

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cypress install
              uses: cypress-io/github-action@v6
              with:
                  runTests: false
                  build: yarn install

    e2e-chrome:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Add PM2
              run: yarn global add pm2

            - name: Run Cypress Heroes in background
              run: pm2 start yarn --name "app" -- run start:ci

            - name: Run E2E Tests
              uses: cypress-io/github-action@v6
              with:
                  browser: chrome

    e2e-firefox:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Add PM2
              run: yarn global add pm2

            - name: Run Cypress Heroes in background
              run: pm2 start yarn --name "app" -- run start:ci

            - name: Run E2E Tests
              uses: cypress-io/github-action@v6
              with:
                  browser: firefox
