name: Cypress Tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    e2e:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Cache yarn packages
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'yarn'

            - name: Install dependencies
              run: |
                  yarn install
                  yarn global add pm2

            - name: Setup Cypress Heroes
              run: yarn run setup

            - name: Run Cypress Heroes in background
              run: pm2 start yarn --name "app" -- run dev

            - name: Run Cypress tests
              run: yarn cypress run --headless --browser chrome

            - name: Stop Cypress Heroes
              run: pm2 delete app
# 