name: Cypress Tests

on: pull_request

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cypress install
              uses: cypress-io/github-action@v6
              with:
                  runTests: false
                  build: yarn run build

            - name: Save build folder
              uses: actions/upload-artifact@v4
              with:
                  name: build-folders
                  if-no-files-found: error
                  path: |
                      app/client/dist
                      app/server/dist

    e2e-chrome:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Download the build folders

              uses: actions/download-artifact@v4
              with:
                  name: build-folders

            - name: Add PM2
              run: yarn global add pm2

            - name: Run Cypress Heroes in background
              run: pm2 start yarn --name "app" -- run start:ci

            - name: Run E2E Tests
              uses: cypress-io/github-action@v6
              with:
                  wait-on: 'http://localhost:3001/heroes, http://localhost:3000'
                  wait-on-timeout: 120
                  browser: chrome

    e2e-firefox:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Download the build folders

              uses: actions/download-artifact@v4
              with:
                  name: build-folders

            - name: Add PM2
              run: yarn global add pm2

            - name: Run Cypress Heroes in background
              run: pm2 start yarn --name "app" -- run start:ci

            - name: Run E2E Tests
              uses: cypress-io/github-action@v6
              with:
                  wait-on: 'http://localhost:3001/heroes, http://localhost:3000'
                  wait-on-timeout: 120
                  browser: firefox
