name: Cypress Tests

on: pull_request

jobs:
    install:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Add PM2
              run: yarn global add pm2

            - name: Cypress install
              uses: cypress-io/github-action@v6
              with:
                  runTests: false
                  build: yarn build

            - name: Lint
              run: yarn lint

            - name: Save build folder
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  if-no-files-found: error
                  path: |
                      app/client/dist
                      app/server/dist

            - name: Start Cypress Heroes in the background
              run: pm2 start yarn --name "app" -- run start:ci


    e2e-chrome:
        runs-on: ubuntu-22.04
        needs: install
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download the build folder
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: |
                      app/client/dist
                      app/server/dist



            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  browser: chrome
                  wait-on: 'http://localhost:3000'
                  wait-on-timeout: 120

    e2e-edge:
        runs-on: ubuntu-22.04
        needs: install
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download the build folder
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: |
                      app/client/dist
                      app/server/dist

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  browser: edge
                  wait-on: 'http://localhost:3000'
                  wait-on-timeout: 120
