name: Cypress Tests

on: pull_request

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cache yarn packages
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'yarn'

            - name: Install
              uses: cypress-io/github-action@v6
              with:
                runTests: false
            - run: yarn cypress info
            - run: yarn install --frozen-lockfile
            - run: yarn global add pm2
            - run: yarn run setup

    e2e-chrome:
      runs-on: ubuntu-latest
      needs: install  
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: E2E Cypress tests using Chrome
          uses: cypress-io/github-action@v6
          with:
            start: pm2 start yarn --name "app" -- run dev
            wait-on: "http://localhost:3000"
            browser: chrome

        - name: Stop Cypress Heroes
          run: pm2 delete app

    e2e-firefox:
      runs-on: ubuntu-latest
      needs: install  
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: E2E Cypress tests using Chrome
          uses: cypress-io/github-action@v6
          with:
            start: pm2 start yarn --name "app" -- run dev
            wait-on: "http://localhost:3000"
            browser: firefox
            
        - name: Stop Cypress Heroes
          run: pm2 delete app
