name: Cypress Tests

on: push

jobs:
    install:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cypress install
              uses: cypress-io/github-action@v6
              with:
                  runTests: false
                  build: yarn install

            - name: Save node_modules
              uses: actions/upload-artifact@v4
              with:
                  name: install
                  if-no-files-found: error
                  path: node_modules

    cypress-run:
        runs-on: ubuntu-22.04
        needs: install
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download the node_modules folder
              uses: actions/download-artifact@v4
              with:
                  name: install
                  path: node_modules

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  start: yarn start
                  browser: chrome
