name: E2E Tests for PRs

on: pull_request

jobs:
    install:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: App and Cypress install
              uses: cypress-io/github-action@v6
              with:
                  runTests: false
            - run: yarn --cwd ./app install
            - run: yarn build

            - name: Save build folder
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  if-no-files-found: error
                  path: |
                      app/client/dist
                      app/server/dist

    eslint:
        runs-on: ubuntu-22.04
        needs: install
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run eslint
              uses: cypress-io/github-action@v6
              with:
                  runTests: false
            - run: yarn lint

    e2e-chrome:
        runs-on: ubuntu-22.04
        needs: eslint
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download the build folder
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: |
                      app/client/dist
                      app/server/dist

            - name: Add PM2
              run: yarn global add pm2

            - name: E2E
              uses: cypress-io/github-action@v6
              with:
                  browser: chrome
                  start: pm2 start yarn --name "app" -- run start:ci
                  wait-on: 'http://localhost:3000, http://localhost:3001/heroes'
                  wait-on-timeout: 100

            - name: Upload screenshots
              uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: cypress-screenshots-chrome
                  path: cypress/screenshots

    e2e-edge:
        runs-on: ubuntu-22.04
        needs: eslint
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download the build folder
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: |
                      app/client/dist
                      app/server/dist

            - name: Add PM2
              run: yarn global add pm2

            - name: E2E
              uses: cypress-io/github-action@v6
              with:
                  browser: edge
                  start: pm2 start yarn --name "app" -- run start:ci
                  wait-on: 'http://localhost:3000, http://localhost:3001/heroes'
                  wait-on-timeout: 100

            - name: Upload screenshots
              uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: cypress-screenshots-edge
                  path: cypress/screenshots
